export { bee } from './bee.ts'
export { bird } from './bird.ts'
export { fish } from './fish.ts'
export { human, humanBody, humanHead, humanTorch, merchantBody } from './human/human.ts'
export { worm } from './worm.ts'
export { firefly } from './firefly.ts'
export { rabbit } from './rabbit.ts'
export { zombie, zombieBody, zombieHead } from './zombie.ts'
export { chick, chicken, egg } from './chicken.ts'
export { skeleton, skeletonBody, skeletonHead } from './skeleton.ts'
export { bat } from './bat.ts'
export { beehive } from './beehive.ts'
export { butterfly } from './butterfly.ts'
export { duck } from './duck.ts'
export { frog } from './frog.ts'
export { snail } from './snail.ts'
export { cow, sheep, sheepShorn } from './livestock.ts'
