export { bee } from './bee.ts'
export { bird } from './bird.ts'
export { fish } from './fish.ts'
export { human, humanBody, humanHead, humanTorch } from './human/human.ts'
export { worm } from './worm.ts'
export { firefly } from './firefly.ts'
export { rabbit } from './rabbit.ts'
export { zombie, zombieBody, zombieHead } from './zombie.ts'
