// Dados mockados da plataforma Yuna. Front-end only — nada aqui vai para uma API.

export const ROLES = {
  admin: {
    id: 'admin',
    label: 'Administração',
    short: 'Admin',
    description: 'Acesso total à agência, equipe e faturamento',
  },
  operacao: {
    id: 'operacao',
    label: 'Operação',
    short: 'Operação',
    description: 'Produção de conteúdo, calendário e publicação',
  },
  comercial: {
    id: 'comercial',
    label: 'Comercial',
    short: 'Comercial',
    description: 'Carteira de clientes, propostas e relacionamento',
  },
  cliente: {
    id: 'cliente',
    label: 'Cliente',
    short: 'Cliente',
    description: 'Aprovação do próprio conteúdo e acompanhamento',
  },
}

export const USERS = {
  admin: {
    name: 'Gustavo Merling',
    email: 'gustavo@yuna.com.br',
    initials: 'GM',
    jobTitle: 'Diretor de operações',
    org: 'Yuna Marketing & Comunicação',
  },
  operacao: {
    name: 'Marina Alves',
    email: 'marina@yuna.com.br',
    initials: 'MA',
    jobTitle: 'Social media sênior',
    org: 'Yuna Marketing & Comunicação',
  },
  comercial: {
    name: 'Rafael Duarte',
    email: 'rafael@yuna.com.br',
    initials: 'RD',
    jobTitle: 'Head comercial',
    org: 'Yuna Marketing & Comunicação',
  },
  cliente: {
    name: 'Helena Bertoldi',
    email: 'helena@casabertoldi.com.br',
    initials: 'HB',
    jobTitle: 'Sócia-proprietária',
    org: 'Casa Bertoldi',
  },
}

// O papel "cliente" só enxerga a própria conta.
export const CLIENT_SCOPE = 'casa-bertoldi'

export const CLIENTS = [
  {
    id: 'casa-bertoldi',
    name: 'Casa Bertoldi',
    handle: '@casabertoldi',
    segment: 'Arquitetura e interiores',
    plan: 'Gestão completa',
    status: 'ativo',
    contact: 'Helena Bertoldi',
    email: 'helena@casabertoldi.com.br',
    phone: '(47) 99682-4071',
    city: 'Joinville, SC',
    since: '2024-03-11',
    monthly: 6800,
    postsMonth: 18,
    color: '#0d3226',
  },
  {
    id: 'clinica-nord',
    name: 'Clínica Nord',
    handle: '@clinicanord',
    segment: 'Saúde e bem-estar',
    plan: 'Gestão completa',
    status: 'ativo',
    contact: 'Dr. André Kruger',
    email: 'andre@clinicanord.com.br',
    phone: '(47) 3025-7712',
    city: 'Joinville, SC',
    since: '2023-08-02',
    monthly: 9200,
    postsMonth: 24,
    color: '#2d3d4d',
  },
  {
    id: 'verde-vivo',
    name: 'Verde Vivo Hortifruti',
    handle: '@verdevivo',
    segment: 'Alimentação',
    plan: 'Conteúdo social',
    status: 'ativo',
    contact: 'Juliana Prass',
    email: 'juliana@verdevivo.com.br',
    phone: '(47) 98811-3390',
    city: 'Blumenau, SC',
    since: '2025-01-20',
    monthly: 4300,
    postsMonth: 12,
    color: '#7b7948',
  },
  {
    id: 'instituto-aurora',
    name: 'Instituto Aurora',
    handle: '@institutoaurora',
    segment: 'Terceiro setor',
    plan: 'Comunicação institucional',
    status: 'ativo',
    contact: 'Beatriz Nunes',
    email: 'bia@institutoaurora.org',
    phone: '(47) 3422-1180',
    city: 'Florianópolis, SC',
    since: '2024-11-05',
    monthly: 3900,
    postsMonth: 10,
    color: '#b48a30',
  },
  {
    id: 'joinville-motors',
    name: 'Joinville Motors',
    handle: '@joinvillemotors',
    segment: 'Automotivo',
    plan: 'Performance + social',
    status: 'onboarding',
    contact: 'Cláudio Meireles',
    email: 'claudio@jvmotors.com.br',
    phone: '(47) 3145-9900',
    city: 'Joinville, SC',
    since: '2026-08-04',
    monthly: 7500,
    postsMonth: 16,
    color: '#4f6f95',
  },
  {
    id: 'fermento-padaria',
    name: 'Fermento Padaria',
    handle: '@fermentopadaria',
    segment: 'Alimentação',
    plan: 'Conteúdo social',
    status: 'pausado',
    contact: 'Otávio Lima',
    email: 'otavio@fermento.com.br',
    phone: '(47) 99120-4455',
    city: 'Joinville, SC',
    since: '2025-06-14',
    monthly: 2600,
    postsMonth: 8,
    color: '#b54141',
  },
]

export const PLATFORMS = {
  instagram: { id: 'instagram', label: 'Instagram' },
  facebook: { id: 'facebook', label: 'Facebook' },
  linkedin: { id: 'linkedin', label: 'LinkedIn' },
}

export const FORMATS = {
  feed: { id: 'feed', label: 'Feed', platforms: ['instagram', 'facebook', 'linkedin'] },
  carrossel: { id: 'carrossel', label: 'Carrossel', platforms: ['instagram', 'facebook', 'linkedin'] },
  stories: { id: 'stories', label: 'Stories', platforms: ['instagram', 'facebook'] },
  reels: { id: 'reels', label: 'Reels', platforms: ['instagram', 'facebook'] },
}

export const STATUS = {
  rascunho: { id: 'rascunho', label: 'Rascunho', tone: 'muted' },
  revisao: { id: 'revisao', label: 'Em revisão', tone: 'info' },
  aprovacao: { id: 'aprovacao', label: 'Aguardando cliente', tone: 'warning' },
  aprovado: { id: 'aprovado', label: 'Aprovado', tone: 'success' },
  publicado: { id: 'publicado', label: 'Publicado', tone: 'primary' },
  ajuste: { id: 'ajuste', label: 'Ajuste solicitado', tone: 'destructive' },
}

// Gradientes de marca usados como placeholder quando a pauta não tem imagem.
export const CREATIVES = {
  verde: 'linear-gradient(150deg, #0d3226 0%, #13523d 58%, #7b7948 100%)',
  marinho: 'linear-gradient(150deg, #2d3d4d 0%, #4f6f95 60%, #b0c1d9 100%)',
  oliva: 'linear-gradient(150deg, #7b7948 0%, #b0a865 55%, #efece5 100%)',
  bege: 'linear-gradient(150deg, #efece5 0%, #e5e0d2 45%, #b9b1a0 100%)',
  ouro: 'linear-gradient(150deg, #b48a30 0%, #d4a04a 55%, #efece5 100%)',
  noite: 'linear-gradient(150deg, #0f1a22 0%, #16242e 50%, #2d3d4d 100%)',
}

// Criativos claros precisam de texto escuro por cima.
export const LIGHT_CREATIVES = ['bege', 'oliva', 'ouro']

export const POSTS = [
  {
    id: 'p-001',
    clientId: 'casa-bertoldi',
    title: 'Projeto Residência Atlântica',
    platform: 'instagram',
    format: 'carrossel',
    status: 'aprovacao',
    date: '2026-08-26T10:00',
    author: 'Marina Alves',
    creative: 'verde',
    image: 'mock/arquitetura-3.jpg',
    caption:
      'Cada ambiente da Residência Atlântica começou com uma pergunta simples: como a luz entra aqui? Arraste para ver o antes, o processo e o resultado.',
    hashtags: '#arquitetura #interiores #joinville #casabertoldi',
    slides: [
      { creative: 'verde', image: 'mock/obra-1.jpg', headline: 'Antes', kicker: 'Estudo de luz' },
      { creative: 'oliva', image: 'mock/arquitetura-2.jpg', headline: 'Processo', kicker: 'Marcenaria sob medida' },
      { creative: 'bege', image: 'mock/arquitetura-3.jpg', headline: 'Depois', kicker: 'Sala integrada' },
      { creative: 'marinho', image: 'mock/arquitetura-4.jpg', headline: 'Detalhe', kicker: 'Pedra e madeira' },
    ],
    metrics: { reach: 0, likes: 0, comments: 0, saves: 0 },
    notes: 'Cliente pediu para revisar a legenda do último slide.',
  },
  {
    id: 'p-002',
    clientId: 'clinica-nord',
    title: 'Agosto Azul — checkup masculino',
    platform: 'instagram',
    format: 'reels',
    status: 'aprovado',
    date: '2026-08-27T18:30',
    author: 'Marina Alves',
    creative: 'marinho',
    image: 'mock/clinica-1.jpg',
    caption:
      'Dois minutos de conversa hoje podem mudar o seu ano inteiro. Agende o checkup e leve alguém com você.',
    hashtags: '#agostoazul #saudedohomem #clinicanord',
    audio: 'Trilha original • Clínica Nord',
    duration: '0:34',
    metrics: { reach: 0, likes: 0, comments: 0, saves: 0 },
    notes: '',
  },
  {
    id: 'p-003',
    clientId: 'verde-vivo',
    title: 'Feira da semana',
    platform: 'instagram',
    format: 'stories',
    status: 'publicado',
    date: '2026-08-24T08:15',
    author: 'Lucas Prado',
    creative: 'oliva',
    image: 'mock/hortifruti-1.jpg',
    caption: 'Chegou a feira da semana. Toque para ver o que entrou hoje.',
    hashtags: '#hortifruti #feira #verdevivo',
    metrics: { reach: 4820, likes: 214, comments: 12, saves: 38 },
    notes: '',
  },
  {
    id: 'p-004',
    clientId: 'instituto-aurora',
    title: 'Relatório de impacto 2026',
    platform: 'linkedin',
    format: 'feed',
    status: 'revisao',
    date: '2026-08-28T09:00',
    author: 'Gustavo Merling',
    creative: 'bege',
    image: 'mock/aurora-1.jpg',
    caption:
      'Publicamos o relatório de impacto do primeiro semestre: 1.240 famílias atendidas, 38 voluntários ativos e três novas frentes de educação. O documento completo está no primeiro comentário.',
    hashtags: '#terceirosetor #impactosocial #institutoaurora',
    metrics: { reach: 0, likes: 0, comments: 0, saves: 0 },
    notes: 'Aguardando número final de voluntários.',
  },
  {
    id: 'p-005',
    clientId: 'casa-bertoldi',
    title: 'Bastidores da obra',
    platform: 'instagram',
    format: 'stories',
    status: 'publicado',
    date: '2026-08-22T16:40',
    author: 'Marina Alves',
    creative: 'noite',
    image: 'mock/obra-1.jpg',
    caption: 'A obra do apartamento Marquês entrou na fase de acabamento.',
    hashtags: '#bastidores #obra',
    metrics: { reach: 3110, likes: 96, comments: 4, saves: 11 },
    notes: '',
  },
  {
    id: 'p-006',
    clientId: 'clinica-nord',
    title: 'Novo aparelho de diagnóstico',
    platform: 'facebook',
    format: 'feed',
    status: 'publicado',
    date: '2026-08-20T11:00',
    author: 'Lucas Prado',
    creative: 'marinho',
    image: 'mock/clinica-2.jpg',
    caption:
      'A Clínica Nord acaba de receber um novo equipamento de diagnóstico por imagem. Exames mais rápidos, laudo no mesmo dia e menos deslocamento para você.',
    hashtags: '#saude #diagnostico #joinville',
    metrics: { reach: 9740, likes: 431, comments: 57, saves: 22 },
    notes: '',
  },
  {
    id: 'p-007',
    clientId: 'joinville-motors',
    title: 'Lançamento linha 2027',
    platform: 'instagram',
    format: 'feed',
    status: 'rascunho',
    date: '2026-09-02T19:00',
    author: 'Marina Alves',
    creative: 'noite',
    image: 'mock/motors-1.jpg',
    caption: 'A linha 2027 chega à concessionária no dia 12. Reserve seu test drive.',
    hashtags: '#lancamento #automotivo #joinvillemotors',
    metrics: { reach: 0, likes: 0, comments: 0, saves: 0 },
    notes: 'Depende da aprovação de imagem pela montadora.',
  },
  {
    id: 'p-008',
    clientId: 'verde-vivo',
    title: 'Receita de sopa de abóbora',
    platform: 'instagram',
    format: 'reels',
    status: 'ajuste',
    date: '2026-08-29T12:00',
    author: 'Lucas Prado',
    creative: 'ouro',
    image: 'mock/hortifruti-2.jpg',
    caption:
      'Três ingredientes, vinte minutos e o cheiro de inverno tomando a casa. Salve para o fim de semana.',
    hashtags: '#receita #inverno #verdevivo',
    audio: 'Áudio em alta • cozinha afetiva',
    duration: '0:48',
    metrics: { reach: 0, likes: 0, comments: 0, saves: 0 },
    notes: 'Cliente pediu para mostrar a marca do caldo no rótulo.',
  },
  {
    id: 'p-009',
    clientId: 'instituto-aurora',
    title: 'Chamada para voluntários',
    platform: 'instagram',
    format: 'carrossel',
    status: 'aprovacao',
    date: '2026-08-30T10:30',
    author: 'Gustavo Merling',
    creative: 'bege',
    image: 'mock/aurora-2.jpg',
    caption:
      'Abrimos 20 vagas de voluntariado para o segundo semestre. Arraste para conhecer as frentes e o tempo de dedicação de cada uma.',
    hashtags: '#voluntariado #institutoaurora',
    slides: [
      { creative: 'bege', image: 'mock/aurora-2.jpg', headline: 'Educação', kicker: '4h por semana' },
      { creative: 'oliva', image: 'mock/aurora-3.jpg', headline: 'Horta', kicker: '3h por semana' },
      { creative: 'verde', image: 'mock/aurora-4.jpg', headline: 'Administrativo', kicker: 'Remoto' },
    ],
    metrics: { reach: 0, likes: 0, comments: 0, saves: 0 },
    notes: '',
  },
  {
    id: 'p-010',
    clientId: 'clinica-nord',
    title: 'Vaga: enfermeiro plantonista',
    platform: 'linkedin',
    format: 'feed',
    status: 'aprovado',
    date: '2026-08-31T08:00',
    author: 'Rafael Duarte',
    creative: 'verde',
    image: 'mock/clinica-3.jpg',
    caption:
      'Estamos contratando enfermeiro plantonista para a unidade centro. Escala 12x36, plano de carreira e apoio para especialização. Candidaturas pelo link na descrição.',
    hashtags: '#vagas #enfermagem #joinville',
    metrics: { reach: 0, likes: 0, comments: 0, saves: 0 },
    notes: '',
  },
  {
    id: 'p-011',
    clientId: 'casa-bertoldi',
    title: 'Paleta do mês: pedra e linho',
    platform: 'instagram',
    format: 'feed',
    status: 'publicado',
    date: '2026-08-18T17:20',
    author: 'Marina Alves',
    creative: 'bege',
    image: 'mock/materiais-1.jpg',
    caption:
      'A paleta deste mês nasceu de duas texturas que quase não pedem licença: pedra bruta e linho cru.',
    hashtags: '#paleta #interiores #materiais',
    metrics: { reach: 6210, likes: 512, comments: 34, saves: 128 },
    notes: '',
  },
  {
    id: 'p-012',
    clientId: 'fermento-padaria',
    title: 'Pão de fermentação natural',
    platform: 'facebook',
    format: 'carrossel',
    status: 'rascunho',
    date: '2026-09-04T09:30',
    author: 'Lucas Prado',
    creative: 'ouro',
    image: 'mock/padaria-1.jpg',
    caption:
      'Vinte e quatro horas de fermentação para uma casca que estala. Arraste para acompanhar o processo desde a massa madre.',
    hashtags: '#fermentacaonatural #padaria',
    slides: [
      { creative: 'ouro', image: 'mock/padaria-2.jpg', headline: 'Massa madre', kicker: 'Dia 1' },
      { creative: 'bege', image: 'mock/padaria-1.jpg', headline: 'Descanso', kicker: '18 horas' },
      { creative: 'oliva', image: 'mock/padaria-3.jpg', headline: 'Forno', kicker: '240°C' },
    ],
    metrics: { reach: 0, likes: 0, comments: 0, saves: 0 },
    notes: 'Conta pausada — publicar somente após retomada do contrato.',
  },
  {
    id: 'p-013',
    clientId: 'joinville-motors',
    title: 'Test drive agendado',
    platform: 'instagram',
    format: 'stories',
    status: 'revisao',
    date: '2026-09-01T14:00',
    author: 'Marina Alves',
    creative: 'marinho',
    image: 'mock/motors-2.jpg',
    caption: 'Agende seu test drive em dois toques.',
    hashtags: '#testdrive',
    metrics: { reach: 0, likes: 0, comments: 0, saves: 0 },
    notes: '',
  },
  {
    id: 'p-014',
    clientId: 'verde-vivo',
    title: 'Parceria com produtores locais',
    platform: 'linkedin',
    format: 'feed',
    status: 'publicado',
    date: '2026-08-14T10:00',
    author: 'Gustavo Merling',
    creative: 'oliva',
    image: 'mock/hortifruti-3.jpg',
    caption:
      'Fechamos parceria com nove famílias produtoras do entorno de Blumenau. O que muda na prática: colheita a 40 km da loja e preço combinado por safra, não por semana.',
    hashtags: '#agriculturafamiliar #varejo',
    metrics: { reach: 5140, likes: 289, comments: 41, saves: 63 },
    notes: '',
  },
]

export const REACH_SERIES = [
  { week: 'Sem 22', instagram: 21400, facebook: 9800, linkedin: 3100 },
  { week: 'Sem 23', instagram: 24800, facebook: 10250, linkedin: 3600 },
  { week: 'Sem 24', instagram: 23150, facebook: 9400, linkedin: 4200 },
  { week: 'Sem 25', instagram: 28600, facebook: 11800, linkedin: 4050 },
  { week: 'Sem 26', instagram: 31200, facebook: 12400, linkedin: 5300 },
  { week: 'Sem 27', instagram: 29800, facebook: 11150, linkedin: 5900 },
  { week: 'Sem 28', instagram: 34500, facebook: 13020, linkedin: 6400 },
  { week: 'Sem 29', instagram: 37900, facebook: 12880, linkedin: 7100 },
]

export const FORMAT_SERIES = [
  { format: 'Feed', posts: 42, engajamento: 4.1 },
  { format: 'Carrossel', posts: 28, engajamento: 6.4 },
  { format: 'Stories', posts: 96, engajamento: 2.8 },
  { format: 'Reels', posts: 24, engajamento: 7.9 },
]

export const TEAM = [
  { name: 'Gustavo Merling', role: 'admin', jobTitle: 'Diretor de operações', initials: 'GM', clients: 6 },
  { name: 'Marina Alves', role: 'operacao', jobTitle: 'Social media sênior', initials: 'MA', clients: 4 },
  { name: 'Lucas Prado', role: 'operacao', jobTitle: 'Social media', initials: 'LP', clients: 3 },
  { name: 'Rafael Duarte', role: 'comercial', jobTitle: 'Head comercial', initials: 'RD', clients: 6 },
  { name: 'Camila Reis', role: 'operacao', jobTitle: 'Designer', initials: 'CR', clients: 5 },
]

export const ACTIVITY = [
  { id: 1, who: 'Helena Bertoldi', what: 'aprovou', target: 'Paleta do mês: pedra e linho', when: 'há 2 horas' },
  { id: 2, who: 'Marina Alves', what: 'enviou para aprovação', target: 'Projeto Residência Atlântica', when: 'há 5 horas' },
  { id: 3, who: 'Juliana Prass', what: 'solicitou ajuste em', target: 'Receita de sopa de abóbora', when: 'ontem' },
  { id: 4, who: 'Rafael Duarte', what: 'cadastrou o cliente', target: 'Joinville Motors', when: 'há 3 dias' },
  { id: 5, who: 'Lucas Prado', what: 'publicou', target: 'Feira da semana', when: 'há 3 dias' },
]

export function clientById(clients, id) {
  return clients.find((c) => c.id === id)
}
